export const GET_EVENTS = "GET_EVENTS";
export const DELETE_EVENT = "DELETE_EVENT";
export const SORT_EVENTS_STARTTIME_ASCENDING =
  "SORT_EVENTS_STARTTIME_ASCENDING";
export const SORT_EVENTS_STARTTIME_DESCENDING =
  "SORT_EVENTS_STARTTIME_DESCENDING";
export const ADD_EVENT = "ADD_EVENT";
