export const GET_EVENTS = "GET_EVENTS";
export const DELETE_EVENT = "DELETE_EVENT";
export const SORT_EVENTS_STARTTIME_ASCENDING =
  "SORT_EVENTS_STARTTIME_ASCENDING";
export const SORT_EVENTS_STARTTIME_DESCENDING =
  "SORT_EVENTS_STARTTIME_DESCENDING";
export const SHOW_TODAYS_EVENTS = "SHOW_TODAYS_EVENTS";
export const ADD_EVENT = "ADD_EVENT";
export const SHOW_WORK_EVENTS = "SHOW_WORK_EVENTS";
