# Generated by Django 3.0.7 on 2020-06-08 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('complete', models.BooleanField()),
                ('todotype', models.CharField(blank=True, choices=[('LONGTERM', 'Longterm'), ('SHORTTERM', 'Shortterm')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('todosowner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
